[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[headers]]
  for = "/*.html"
  [headers.values]
    Permissions-Policy = "microphone=(*)"
    X-Frame-Options = "SAMEORIGIN"

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"